sudo: false

python: "3.6"

language: python

services:
  - postgresql

env:
  global:
    - DATABASE_URL=postgresql://postgres@localhost:5432/carbondoomsday
    - DJANGO_CONFIGURATION=Development
    - DJANGO_SECRET_KEY=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    - DJANGO_SETTINGS_MODULE=carbondoomsday.settings
    - CELERY_BROKER_URL=redis://localhost:6379
    - CELERY_RESULT_BACKEND=redis://localhost:6379

matrix:
  fast_finish: true
  include:
    - env: BUILD=quality
    - env: BUILD=migrate
    - env: BUILD=test

before_install:
  - psql -c 'create database carbondoomsday;' -U postgres
  - psql -c 'create database carbondoomsday_test;' -U postgres
  - pip install -U pip -e .

install:
  - |
    set -ex
    case "$BUILD" in
      quality)
        pip install -r requirements/quality.txt
        ;;
      migrate)
        pip install -r requirements.txt
        ;;
      test)
        pip install -r requirements/test.txt
        ;;
    esac
    set +ex

script:
  - |
    set -ex
    case "$BUILD" in
      quality)
        make isort
        make lint
        ;;
      migrate)
        make check_migrations
        make migrate
        ;;
      test)
        make test
        ;;
    esac
    set +ex

notifications:
  email: false
